import { test, expect } from './fixture.js';
import type { Run } from '../../src/types.js';
import { crosscurrentGroup, crosscurrentLineId, crosscurrentParse, crosscurrentRestingLine, crosscurrentShift, type CrosscurrentState } from '../../src/games/crosscurrent.js';
import { replay } from '../../src/games/referee.js';

test('Crosscurrent: cooldown default, resting line, edge progress, completion and replay', async ({ page, room }, info) => {
  test.setTimeout(120_000);
  await page.goto(room.url);
  await page.getByRole('radio', { name: 'Gamer', exact: true }).click();
  await room.service.call('resources.configure', { maxActiveAgents: 6, requestId: 'crosscurrent-limit' });
  await page.getByRole('button', { name: 'Activate both', exact: true }).click();
  await page.getByRole('alertdialog').getByRole('button', { name: 'Activate anyway', exact: true }).click();
  const setup = page.getByRole('region', { name: 'Game setup', exact: true });
  const kinds = setup.getByRole('radiogroup', { name: 'Game', exact: true });
  await expect(kinds.getByRole('radio')).toHaveText(['Chess', 'Checkers', 'Go', 'Crosscurrent']);
  await kinds.getByRole('radio', { name: 'Go', exact: true }).click();
  await setup.getByRole('radiogroup', { name: 'Go board size' }).getByRole('radio', { name: '13×13', exact: true }).click();
  await kinds.getByRole('radio', { name: 'Crosscurrent', exact: true }).click();
  await expect(setup.getByRole('radiogroup', { name: 'Crosscurrent board size' })).toHaveCount(0);
  await expect(setup.getByText('7×7 · one shared star · Three Edges + cooldown', { exact: true })).toBeVisible();
  const progress = page.getByRole('region', { name: 'Crosscurrent edge progress' });
  await expect(progress.getByText('Reach any 3 edges')).toBeVisible();
  await expect(progress.locator('.reached')).toHaveCount(0);
  await expect(progress.getByLabel('Resting line')).toHaveText('Resting: none · first turn');
  await expect(page.getByRole('region', { name: 'Crosscurrent rules' })).toContainText('any row left or right, or any column up or down');
  const board = page.getByRole('img', { name: 'Crosscurrent board, 7 by 7', exact: true });
  await expect(board.locator('.cell')).toHaveCount(49);
  await expect(board.locator('.crosscurrent-star')).toHaveCount(1);
  await expect(board.locator('desc')).toContainText('D4 neutral star');
  await page.screenshot({ path: info.outputPath('crosscurrent-setup.png') });
  for (const oldSize of [3, 5]) {
    await page.evaluate(size => localStorage.setItem('ava-game', JSON.stringify({ kind: 'crosscurrent', size: 13, crosscurrentSize: size, first: 'cli1', minutes: 5 })), oldSize);
    await page.reload();
    await expect(board.locator('.cell')).toHaveCount(49);
    await expect(board.locator('.crosscurrent-star')).toHaveCount(1);
    await expect(setup.getByRole('radio', { name: /3×3|5×5/ })).toHaveCount(0);
  }
  await kinds.getByRole('radio', { name: 'Go', exact: true }).click();
  await expect(setup.getByRole('radiogroup', { name: 'Go board size' }).getByRole('radio', { name: '13×13', exact: true })).toBeChecked();
  await kinds.getByRole('radio', { name: 'Crosscurrent', exact: true }).click();
  await setup.getByRole('radio', { name: 'Claude Code', exact: true }).click();
  // The actual in-app panel can be narrow: clicking Start scrolls below the board to reach setup.
  await page.setViewportSize({ width: 714, height: 870 });
  await setup.getByRole('button', { name: 'Start crosscurrent', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Crosscurrent 7x7: Claude Code (Circle) vs Codex (Diamond)', exact: true })).toBeVisible({ timeout: 20_000 });
  await expect.poll(() => page.locator('.game-view').evaluate(element => element.scrollTop)).toBe(0);
  const narrowPane = (await page.locator('.game-view').boundingBox())!, narrowBoard = (await board.boundingBox())!;
  expect(narrowBoard.y).toBeGreaterThanOrEqual(narrowPane.y);
  expect(narrowBoard.y + narrowBoard.height).toBeLessThanOrEqual(narrowPane.y + narrowPane.height);
  await page.screenshot({ path: info.outputPath('crosscurrent-narrow-start.png') });
  await page.setViewportSize({ width: 1280, height: 900 });
  const gameRun = (): Run | undefined => {
    const record = room.service.store.db.prepare("SELECT data FROM pairs WHERE thread LIKE 'room-mode:%:game'").get() as { data: string } | undefined;
    const pair = record ? JSON.parse(record.data) as { activeRunId?: string; lastRunId?: string } : undefined;
    const id = pair?.activeRunId ?? pair?.lastRunId;
    return id ? room.service.store.run(id) : undefined;
  };
  await expect.poll(() => gameRun()?.status, { timeout: 90_000 }).toBe('completed');
  const run = gameRun()!;
  expect(run.config.game).toMatchObject({ kind: 'crosscurrent', size: 7, ruleset: 'three-edges-cooldown-v3', first: 'cli2' });
  expect(run.game?.illegal).toEqual({ cli1: 0, cli2: 0 });
  expect(run.reason).toBe('game_over');
  expect(room.service.store.db.prepare("SELECT count(*) n FROM direct_messages WHERE sender='user' AND text LIKE '%You are about to play Crosscurrent%'").get()).toEqual({ n: 2 });
  const recorded = room.service.store.messages(run.id).filter(m => m.sender !== 'user');
  for (const move of recorded) expect(move.text).toMatch(/^[A-G][1-7] (ROW [1-7] (LEFT|RIGHT)|COL [A-G] (UP|DOWN))$/);
  const final = replay(run.config.game!, recorded.map(m => m.text)) as CrosscurrentState;
  const lines = recorded.map(m => crosscurrentLineId(7, crosscurrentParse(7, m.text)!));
  for (let i = 1; i < lines.length; i++) expect(lines[i]).not.toBe(lines[i - 1]);
  await expect(progress.getByLabel('Resting line')).toContainText(crosscurrentRestingLine(final)!.name);
  await expect(board.locator('.resting')).toHaveCount(7);
  await expect(board.locator('.cooldown-outline')).toHaveCount(1);
  for (const color of [1, 2] as const) {
    const edges = crosscurrentGroup(final, color).edges;
    const player = progress.getByRole('group', { name: `${color === 1 ? 'Circle' : 'Diamond'} edge progress` });
    await expect(player.locator('.reached')).toHaveCount(edges.filter(Boolean).length);
    await expect(player).toContainText(`${edges.filter(Boolean).length} of 4 reached`);
  }
  expect(recorded.length).toBeLessThanOrEqual(48);
  await expect(board.locator('.crosscurrent-stone')).toHaveCount(recorded.length);
  await expect(board.locator('.crosscurrent-star')).toHaveCount(1);
  await expect(board.locator('.shifted')).toHaveCount(7);
  await expect(board.locator('.new-stone')).toHaveCount(1);
  const players = page.getByRole('region', { name: 'Players', exact: true });
  await expect(players.getByRole('status')).toContainText(/wins|Draw:/);
  await expect.poll(() => page.locator('.game-side').evaluate(element => element.scrollTop)).toBe(0);
  await page.screenshot({ path: info.outputPath('crosscurrent-finished.png') });
  const moves = page.getByRole('region', { name: 'Moves', exact: true });
  await moves.getByRole('button', { name: 'First position', exact: true }).click();
  await expect(board.locator('.crosscurrent-stone')).toHaveCount(0);
  await expect(board.locator('.crosscurrent-star')).toHaveCount(1);
  await expect(board.locator('desc')).toContainText('D4 neutral star');
  await expect(board.locator('.shifted')).toHaveCount(0);
  await expect(progress.locator('.reached')).toHaveCount(0);
  await expect(progress.getByLabel('Resting line')).toHaveText('Resting: none · first turn');
  await expect(board.locator('.cooldown-outline')).toHaveCount(0);
  await moves.getByRole('button', { name: 'Next move', exact: true }).click();
  await expect(board.locator('.crosscurrent-stone')).toHaveCount(1);
  const firstShift = crosscurrentShift(7, crosscurrentParse(7, recorded[0]!.text)!);
  const firstStone = firstShift.destination;
  const firstGroup = board.locator('.crosscurrent-stone.circle');
  await expect(firstGroup.locator('circle').first()).toHaveAttribute('cx', String(32 + (firstStone % 7 + .5) * 48));
  await expect(firstGroup.locator('circle').first()).toHaveAttribute('cy', String(32 + (Math.floor(firstStone / 7) + .5) * 48));
  await expect(page.getByRole('region', { name: 'Crosscurrent rules' }).getByRole('status')).toContainText(`Move shown: ${recorded[0]!.text}`);
  const firstState = replay(run.config.game!, [recorded[0]!.text]) as CrosscurrentState;
  await expect(progress.getByLabel('Resting line')).toContainText(crosscurrentRestingLine(firstState)!.name);
  await expect(board.locator('desc')).toContainText(`Resting line: ${crosscurrentRestingLine(firstState)!.name}`);
  await moves.getByRole('button', { name: 'Latest position', exact: true }).click();
  await page.reload();
  await expect(board.locator('.crosscurrent-stone')).toHaveCount(recorded.length);
  await expect(players.getByRole('status')).toContainText(run.game!.result!.reason);
  await expect(progress.getByLabel('Resting line')).toContainText(crosscurrentRestingLine(final)!.name);
  await page.getByRole('button', { name: 'New game', exact: true }).click();
  await kinds.getByRole('radio', { name: 'Go', exact: true }).click();
  await expect(page.getByRole('img', { name: 'Go board, 13 by 13', exact: true })).toBeVisible();
  await kinds.getByRole('radio', { name: 'Crosscurrent', exact: true }).click();
  const preview = page.getByRole('img', { name: 'Crosscurrent board, 7 by 7', exact: true });
  await expect(preview.locator('.crosscurrent-stone')).toHaveCount(0);
  await expect(preview.locator('.crosscurrent-star')).toHaveCount(1);
  await expect(progress.getByLabel('Resting line')).toHaveText('Resting: none · first turn');
  await page.setViewportSize({ width: 390, height: 844 });
  const split = page.getByRole('separator', { name: 'Resize the CLI and lower panes', exact: true });
  await split.focus();
  for (let i = 0; i < 8; i++) await split.press('ArrowUp');
  const box = await preview.boundingBox();
  expect(box).not.toBeNull(); expect(box!.x).toBeGreaterThanOrEqual(0); expect(box!.x + box!.width).toBeLessThanOrEqual(390);
  await page.screenshot({ path: info.outputPath('crosscurrent-mobile.png') });
  await page.setViewportSize({ width: 1280, height: 900 });
  await setup.getByRole('button', { name: 'Back to this game', exact: true }).click();
  await expect(board.locator('.crosscurrent-stone')).toHaveCount(recorded.length);
  // Fault injection is confined to this disposable test pool; saved failures must not look like a valid final board.
  room.service.store.db.prepare('UPDATE messages SET text=? WHERE id=?').run('A1 ROW 99 LEFT', recorded.at(-1)!.id);
  await page.reload();
  await expect(page.getByRole('alert')).toContainText(`Recorded move ${recorded.length}`);
  await expect(page.getByRole('alert')).toContainText('cannot be replayed');
  await expect(board.locator('.crosscurrent-stone')).toHaveCount(recorded.length - 1);
  await expect(page.getByRole('button', { name: 'A1 ROW 99 LEFT', exact: true })).toBeDisabled();
  await expect(players.getByRole('status')).toContainText('Recorded result:');
  await page.screenshot({ path: info.outputPath('crosscurrent-bad-replay.png') });
  room.service.store.updateRun(run.id, saved => { saved.config.game!.ruleset = 'future-v99' as 'three-edges-cooldown-v3'; });
  await page.reload();
  await expect(page.getByRole('alert')).toContainText('Unsupported Crosscurrent ruleset');
  await expect(page.getByText('Board unavailable for this saved game.', { exact: true })).toBeVisible();
  await expect(board).toHaveCount(0);
});

for (const ruleset of ['classic-v1', 'three-edges-v2'] as const) test(`Crosscurrent: ${ruleset} history keeps its rules and replay; the next game defaults to cooldown`, async ({ page, room }) => {
  test.setTimeout(90_000);
  await page.goto(room.url);
  await page.getByRole('radio', { name: 'Gamer', exact: true }).click();
  await room.service.call('resources.configure', { maxActiveAgents: 6, requestId: 'classic-limit' });
  await page.getByRole('button', { name: 'Activate both', exact: true }).click();
  await page.getByRole('alertdialog').getByRole('button', { name: 'Activate anyway', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Start chess', exact: true })).toBeEnabled({ timeout: 20_000 });
  const record = room.service.store.db.prepare("SELECT id FROM pairs WHERE thread LIKE 'room-mode:%:game'").get() as { id: string };
  const run = await room.service.call('run.start', { pairId: record.id, text: `${ruleset} history fixture`, requestId: 'classic-history', options: { mode: 'game', paceMs: 0, game: { kind: 'crosscurrent', ruleset, size: 7, first: 'cli1', moveMs: 300_000, maxIllegal: 3 } } }) as Run;
  await expect.poll(() => room.service.store.run(run.id).status, { timeout: 60_000 }).toBe('completed');
  // Saved J8/J10 games predate ruleset metadata. Only this disposable fixture loses the version.
  if (ruleset === 'classic-v1') room.service.store.updateRun(run.id, saved => { delete saved.config.game!.ruleset; });
  const saved = room.service.store.run(run.id), moves = room.service.store.messages(run.id).filter(m => m.sender !== 'user').map(m => m.text);
  expect(moves.every(m => ruleset === 'classic-v1' ? /^[A-G][1-7] (LEFT|RIGHT|UP|DOWN)$/.test(m) : /^[A-G][1-7] (ROW|COL) /.test(m))).toBe(true);
  const final = replay(saved.config.game!, moves) as CrosscurrentState;
  expect(final.ruleset).toBe(ruleset); expect(final.resting).toBe(null);
  await page.reload();
  const board = page.getByRole('img', { name: 'Crosscurrent board, 7 by 7' });
  await expect(board.locator('.crosscurrent-stone')).toHaveCount(moves.length);
  await expect(page.getByRole('region', { name: 'Crosscurrent edge progress' })).toContainText(ruleset === 'classic-v1' ? 'Connect opposite edges' : 'Reach any 3 edges');
  await expect(page.getByRole('region', { name: 'Crosscurrent rules' })).toContainText(ruleset === 'classic-v1' ? 'top and bottom or left and right' : 'at least three of the four edges');
  await expect(page.locator('.crosscurrent-cooldown')).toHaveCount(0); await expect(board.locator('.cooldown-outline')).toHaveCount(0);
  await expect(page.getByRole('region', { name: 'Players' }).getByRole('status')).toContainText(saved.game!.result!.reason);
  await page.getByRole('button', { name: 'First position', exact: true }).click();
  await expect(board.locator('.crosscurrent-stone')).toHaveCount(0);
  await page.getByRole('button', { name: 'Latest position', exact: true }).click();
  await expect(board.locator('.crosscurrent-stone')).toHaveCount(moves.length);
  await page.getByRole('button', { name: 'New game', exact: true }).click();
  await page.getByRole('region', { name: 'Game setup' }).getByRole('radio', { name: 'Crosscurrent', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Crosscurrent edge progress' })).toContainText('Reach any 3 edges');
  await expect(page.getByLabel('Resting line', { exact: true })).toHaveText('Resting: none · first turn');
  await expect(board.locator('.crosscurrent-stone')).toHaveCount(0);
});
