import type { DebateSetup, SavedPrompt } from './prompt-types.js';
import type { AnswerCheck } from './types.js';

// Built-in Debate prompts (G8): formal motions, each side assigned, as in competitive debate. Every debater gets a private
// brief (through its 1:1 line before the debate starts) with its strongest lines of argument, the evidence to find, and
// what the other side will say. Motions are real trade-offs with evidence on both sides, so seven rounds hold up.
export type Starter = Pick<SavedPrompt, 'id' | 'name' | 'mode' | 'buildKind' | 'text'> & { debate?: DebateSetup; check?: AnswerCheck; build?: SavedPrompt['build'] };

const debate = (proposition: string, opposition: string, internet = true, rounds = 7): DebateSetup =>
  ({ rounds, agents: { cli1: { stance: 'for', context: proposition, internet }, cli2: { stance: 'against', context: opposition, internet } } });
const starter = (id: string, name: string, motion: string, definitions: string, setup: DebateSetup): Starter =>
  ({ id, name, mode: 'conversation', buildKind: 'build', text: `# Motion: ${motion}\n\n${definitions}`, debate: setup });

export const DEBATE_STARTERS: Starter[] = [
  starter('debate-smartphones-schools', 'Ban smartphones in schools', 'This house would ban smartphones in schools',
    'Schools means primary and secondary schools. The ban covers the whole school day, breaks included, with exceptions for medical needs.',
    debate('Your strongest lines: attention and learning, bullying and social pressure during the day, and the countries and school systems that have introduced bans. Find the studies and the official evaluations of those bans. Expect the Opposition to say the evidence is mixed, that parents want contact for safety, and that schools should teach responsible use instead; have answers ready.',
      'Your strongest lines: the evidence on bans is weaker and more mixed than headlines suggest, enforcement costs teachers time, phones matter for safety and for students with additional needs, and schools should teach digital skills rather than avoid them. Find the studies that found small or no effects. Expect the Proposition to cite countries and schools that report improvements; question how those results were measured.')),
  starter('debate-social-media-teens', 'Social media and teenagers', 'This house believes social media has done more harm than good to teenagers',
    'Social media means feed-based platforms such as Instagram, TikTok and Snapchat. Teenagers means 13 to 17 year olds.',
    debate('Your strongest lines: the rise in teenage anxiety, depression and self-harm since the early 2010s, experimental and natural-experiment studies, and platform design built for engagement. Find the researchers and data on both sides of this argument (it is a live academic dispute). Expect the Opposition to say the correlations are small and causation is unproven; answer with the experimental evidence and the timing.',
      'Your strongest lines: the measured associations are small, causation is disputed by leading researchers, other causes explain the trends, and social media gives teenagers connection, information and community, especially minorities and isolated teens. Find the meta-analyses and the critiques of the harm case. Expect the Proposition to cite the timing of the mental-health trends; answer on causation and alternative explanations.')),
  starter('debate-nuclear-power', 'Nuclear power and climate', 'This house believes nuclear power should be at the heart of the fight against climate change',
    'At the heart means a central part of how countries cut emissions from electricity, with new reactors built, not only existing ones kept open.',
    debate('Your strongest lines: firm low-carbon power that runs day and night, the safety record per unit of energy, land use, and grids that decarbonized with nuclear. Find the figures on deaths per terawatt-hour, capacity factors and the countries that built out nuclear. Expect the Opposition to argue cost overruns, build times and that renewables are cheaper; answer with system costs and firm capacity.',
      'Your strongest lines: new nuclear is slow and expensive, with recent projects far over budget and years late, while solar, wind and storage costs have fallen fast; money and time matter in a climate emergency. Find the costs and schedules of recent reactor projects and the latest cost comparisons. Expect the Proposition to argue reliability and land use; answer with storage, grids and the opportunity cost.')),
  starter('debate-universal-basic-income', 'Universal basic income', 'This house would introduce a universal basic income',
    'A regular cash payment to every adult, without conditions, set high enough to cover basic needs, replacing some existing benefits.',
    debate('Your strongest lines: security and freedom for workers, the costs and gaps of means-tested welfare, preparation for automation, and what cash-transfer studies and pilots found about work and wellbeing. Find the pilots and their results. Expect the Opposition to argue cost and reduced work; answer with the evidence on employment and how it could be funded.',
      'Your strongest lines: the cost at a meaningful level, the taxes it would need, money spent on people who don’t need it instead of those who do, and that pilots were small, temporary and not universal. Find the costings and the limits of the pilot evidence. Expect the Proposition to cite pilots; answer on scale, duration and funding.')),
  starter('debate-rent-control', 'Rent control', 'This house believes rent control does more harm than good',
    'Rent control means legal limits on how much rents can rise for existing tenants.',
    debate('Your strongest lines: the economic consensus that rent control reduces housing supply and quality, misallocates housing, and helps current tenants at the expense of future ones. Find the major empirical studies of cities that introduced it. Expect the Opposition to argue stability for tenants and displacement; answer with the long-run supply effects.',
      'Your strongest lines: tenants’ stability, preventing displacement and sudden rent shocks, that modern rent stabilization differs from old hard caps, and that supply depends mostly on zoning. Find the evidence on displacement and on newer designs. Expect the Proposition to cite economists and supply studies; answer that those effects can be designed around.')),
  starter('debate-four-day-week', 'The four-day week', 'This house would make the four-day working week the standard',
    'Standard means the normal full-time week becomes four days, with the same pay and no increase in daily hours.',
    debate('Your strongest lines: productivity, wellbeing, retention, and the results of the large trials of a four-day week. Find the trial reports and what share of companies kept the policy. Expect the Opposition to argue that trials were self-selected and that many jobs can’t compress hours; answer with sector examples and long-run results.',
      'Your strongest lines: trial companies chose to take part, results may not last or generalize, services such as health care need cover every day, and costs for small businesses. Find the critiques of the trials and examples of companies that dropped it. Expect the Proposition to cite the trial results; answer on selection and on sectors left out.')),
  starter('debate-open-ai-models', 'Open AI models', 'This house believes releasing the weights of frontier AI models does more good than harm',
    'Frontier models are the most capable AI models of their time. Releasing the weights means anyone can download, run and modify them.',
    debate('Your strongest lines: innovation and competition, independent safety research, transparency, avoiding concentration of power in a few companies, and the open-source record in software. Find examples of research and products built on open models. Expect the Opposition to argue misuse; answer on marginal risk and the benefits of scrutiny.',
      'Your strongest lines: weights can’t be recalled once released, safeguards can be removed by fine-tuning, misuse risks grow with capability, and adversaries gain capabilities for free. Find the evidence on safeguard removal and misuse. Expect the Proposition to argue innovation and openness; answer that the most capable models are different and that staged access exists.')),
  starter('debate-kidney-market', 'A market for kidneys', 'This house would allow a regulated market for kidney donations',
    'Living donors could be paid a set amount by a public body, with screening, consent rules and follow-up care; organs would still be allocated by medical need.',
    debate('Your strongest lines: people die on waiting lists, dialysis costs and suffering, the low risk of living donation, and the one country with a legal paid system. Find the waiting-list figures and the evidence from that system. Expect the Opposition to argue exploitation of the poor and crowding out of altruism; answer with regulation and fixed public payment.',
      'Your strongest lines: exploitation of poor and vulnerable donors, coerced consent, the record of organ trade, damage to altruistic donation, and alternatives such as opt-out systems. Find the evidence on donor outcomes in paid systems and on opt-out reforms. Expect the Proposition to cite waiting lists; answer with alternatives that raise supply without payment.')),
  starter('debate-youth-tackle-football', 'Youth tackle football', 'This house would ban tackle football for children under 14',
    'The ban applies to organized tackle football; flag football and other forms without tackling stay allowed.',
    debate('Your strongest lines: repeated head impacts in developing brains, research on early exposure and later brain health, and that flag football teaches the same skills. Find the studies on age of first exposure and head impacts in youth football. Expect the Opposition to argue the evidence is uncertain and that benefits and parental choice matter; answer with precaution for children.',
      'Your strongest lines: the evidence on youth play is uncertain, safety rules and coaching have changed, exercise and team benefits are real, children may switch to riskier activities, and parents should decide. Find the studies that found no link and the effects of rule changes. Expect the Proposition to cite brain research; answer on uncertainty, age and alternatives.')),
  starter('debate-fall-of-rome', 'The fall of Rome', 'This house believes the Western Roman Empire fell mainly because of internal causes',
    'Internal causes include political instability, civil wars, the economy, taxation and the army. External causes include the Huns, the Goths and other migrations and invasions. The period is roughly 376 to 476 AD.',
    debate('Your strongest lines: civil wars and usurpations that drained the army, fiscal and economic strain, political division between East and West, and that the Eastern Empire survived the same outside pressure. Use the historians who stress internal decline. Expect the Opposition to cite the Huns and the Gothic wars; answer that internal weakness turned pressure into collapse.',
      'Your strongest lines: the empire was coping until the Huns pushed peoples across the frontier, the disasters of Adrianople and the loss of Africa’s tax revenue were external blows, and historians who argue the fall was not inevitable. Expect the Proposition to cite civil wars and decline; answer that the East had the same problems and survived, so the outside shock decided it.', false)),
];
// Harder debates (G15): technical motions where the easy talking points lose. Winning needs exact evidence and real
// clash on mechanisms, and two are closed book (internet off), so each side argues from what it knows and the judge
// tests every claim.
export const HARD_DEBATES: Starter[] = [
  starter('debate-ranked-choice', 'Ranked-choice voting (hard)', 'This house would replace first-past-the-post with instant-runoff voting for single-winner elections',
    'Instant-runoff voting (often called ranked-choice voting) means voters rank candidates; the candidate with the fewest first preferences is eliminated and their ballots transfer to the next preference until someone has a majority of the ballots still in play. It is used for Australia’s House of Representatives and in Maine and Alaska.',
    debate('Your strongest lines: it removes most spoiler effects, the winner has majority support among continuing ballots, campaigns must court second preferences, and a century of Australian use plus recent US experience. Find the evidence on spoilers, civility and voter understanding. Expect the Opposition to cite non-monotonicity, the Alaska 2022 special election and ballot exhaustion; answer with how rarely those occur and how first-past-the-post fails worse on the same tests.',
      'Your strongest lines: instant-runoff can eliminate the candidate who would beat every other one-on-one (center squeeze), it is non-monotonic (ranking a candidate higher can make them lose), exhausted ballots can leave the winner without a majority of all voters, Australia still has a two-party system, and better reforms exist (approval or Condorcet methods). Find Burlington 2009 and Alaska 2022 and the exact counts. Expect the Proposition to argue spoilers and majorities; answer that instant-runoff only hides the spoiler problem and its majority is manufactured.')),
  starter('debate-replication-crisis', 'The replication crisis (hard)', 'This house believes most published findings in social psychology should not be trusted',
    'Published findings means results reported in peer-reviewed social psychology journals. Should not be trusted means a reader should not act on a finding as true without an independent replication.',
    debate('Your strongest lines: large replication projects in which well under half of published effects replicated, replicated effects much smaller than the originals, low statistical power, flexible analyses and publication bias, and famous effects that collapsed. Find the projects and their exact rates. Expect the Opposition to argue that reforms fixed it and that failed replications can be wrong; answer with what share of the literature predates the reforms and how much it is still cited.',
      'Your strongest lines: replication rates vary widely by field, method and sample, a failed replication isn’t proof a finding is false, the projects sampled particular journals and years, preregistered high-powered studies replicate at much higher rates, and the field changed its practices after 2015. Find the evidence on newer replication rates and on how prediction markets picked the studies that would replicate. Expect the Proposition to cite the headline rates; answer on what they do and don’t show.')),
  starter('debate-ngdp-targeting', 'Nominal GDP targeting (hard)', 'This house would have central banks target a path for the level of nominal GDP instead of an inflation rate',
    'A nominal GDP level target means the central bank aims to keep total spending in the economy (nominal GDP) on a set growth path, and makes up for misses, instead of aiming at an inflation rate and letting bygones be bygones.',
    debate('Your strongest lines: it responds correctly to supply shocks (looking through them instead of tightening into them), level targeting makes up for shortfalls such as the slow recovery after 2008, it works at the zero lower bound through expectations, and it stabilizes debt burdens. Find the economists and models behind it and what a nominal GDP path would have implied in 2008 and 2021. Expect the Opposition to argue data revisions and credibility; answer with forecast targeting and the record of inflation targeting’s misses.',
      'Your strongest lines: nominal GDP is measured late, quarterly and revised heavily, the public understands inflation but not nominal GDP, a level target can demand high inflation after a slump that people won’t accept, falling trend growth makes the path wrong, and inflation targeting already allows flexibility. Find the evidence on revisions and on the central banks that considered and rejected it. Expect the Proposition to argue supply shocks and 2008; answer that average inflation targeting already covers that.')),
  starter('debate-strategic-bombing', 'Strategic bombing of Germany (hard)', 'This house believes the Allied strategic bombing campaign against Germany was a strategic mistake',
    'The campaign means the British and American bombing of German cities, industry and transport from 1940 to 1945. A strategic mistake means the same resources would have done more to win the war if used elsewhere. The moral question is outside the motion. No internet: argue from what you know, and expect the judge to test every figure you give.',
    debate('Your strongest lines: German war production rose until mid-1944 despite the bombing, area bombing of cities did not break morale, the cost in aircrew and in industrial effort (a large share of British war production) was enormous, and those resources could have closed the Atlantic air gap sooner or supported the armies. Use the postwar bombing surveys and the historians who stress its limits. Expect the Opposition to argue the oil campaign and the diversion of German air defenses; answer that those came late, and that the area campaign was most of the effort.',
      'Your strongest lines: the bombing forced Germany to divert hundreds of thousands of men and thousands of guns and fighters to air defense, away from the Eastern Front; it capped production below what Germany would otherwise have reached; the 1944 oil and transport campaigns crippled the Luftwaffe and the army; and it destroyed the Luftwaffe’s fighter force before D-Day. Use the historians who argue its indirect effects. Expect the Proposition to cite rising production; answer with production that would have been and with the diversion.', false)),
  starter('debate-industrial-living-standards', 'Living standards in the Industrial Revolution (hard)', 'This house believes ordinary British workers were no better off in 1840 than in 1780',
    'Ordinary workers means manual workers and their families. Better off means their real wages, health, life expectancy and working conditions taken together. No internet: argue from what you know, and expect the judge to test every figure you give.',
    debate('Your strongest lines: real wage series that rose little until the 1840s, rising heights falling in the cohorts born around the 1820s and 1830s, worse urban mortality, longer working hours and child labor, and a growing share of income going to profits. Use the economic historians on the pessimist side and the data they built. Expect the Opposition to cite real wage gains and cheaper goods; answer with what the price indices leave out and the health evidence.',
      'Your strongest lines: real wages did rise over the period once cheaper manufactured goods are counted, the wars with France explain the pause, population grew fast while living standards held or rose (unlike before), and consumption of goods such as tea, sugar and cotton clothing spread to workers. Use the economic historians on the optimist side and their wage and price series. Expect the Proposition to cite heights and mortality; answer with what drove them and with the trend after 1820.', false)),
];
// Starters retired by later sets, by ID, with fingerprints of each version as shipped (name, prompt.md and debate.json).
// A library's copy that still matches is removed; an edited copy is the user's and stays.
export const RETIRED_STARTERS: Record<string, string[]> = {
  'starter-debate-car-ban': ['8fd30f1ba4f1eeacd0e3c8aa'], 'starter-debate': ['54c02871faa2386e7af8597e', 'c1d0af8d9fe326a5ff13903b'],
  'starter-vikings': ['84c232efcc94039373270d1a', 'b67b7015bd2a40540965cf27'], 'starter-debate-industrial': ['f2acdb18d1c4d2167b5b2485'],
  'starter-debate-mammoth': ['25faa989a4f2f83f593cc669'], 'starter-debate-ai-code': ['b4d4202904114f36d1b876c9'],
  'starter-debate-car-sale': ['7aef94ff6af2503c773c2516'], 'starter-debate-detective': ['4df0a53c76afd32dfd314b44'],
  'starter-debate-pitch': ['d2c35093cda0fbf71d98411b'], 'starter-debate-hot-dog': ['3b36dcf027a4324f1ee04efe'],
};
